import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import Header from "../components/Header";
import { setloading, setFreeCount } from "../redux/authslice";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable"; // 🆕 For tabular formatting

function GenPaper() {
  const [formData, setFormData] = useState({
    topic: "",
    classLevel: "",
    totalMarks: "",
    difficulty: "",
    pattern: "",
  });

  const [generatedPaper, setGeneratedPaper] = useState("");
  const [error, setError] = useState("");
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { isAuthenticated, isloading } = useSelector((state) => state.auth);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleGenerate = async (event) => {
    event.preventDefault();

    if (!isAuthenticated) {
      navigate("/login");
      return;
    }

    const { topic, classLevel, totalMarks, difficulty } = formData;
    if (!topic || !classLevel || !totalMarks || !difficulty) {
      setError("Please fill all required fields marked with *");
      return;
    }

    setError("");
    setGeneratedPaper("");
    dispatch(setloading(true));

    try {
      const res = await axios.post("http://localhost:4000/genpaper", formData, {
        withCredentials: true,
      });

      setGeneratedPaper(res.data.paper);
      dispatch(setFreeCount(res.data.freeCount));
    } catch (err) {
      if (err.response?.status === 403) {
        setError("You have used all your free paper generations.");
      } else if (err.response?.status === 401) {
        setError("Please log in again. Session expired.");
        navigate("/login");
      } else {
        setError("Server error. Please try again later.");
      }
    } finally {
      dispatch(setloading(false));
    }
  };

  // 🆕 Professional PDF Generator
  const handleDownloadPDF = () => {
    const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
    const margin = 40;
    const pageWidth = doc.internal.pageSize.getWidth();
    const centerX = pageWidth / 2;

    // 🎓 Header
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Question Paper", centerX, 60, { align: "center" });

    doc.setFontSize(12);
    doc.setFont("Helvetica", "normal");
    doc.text(`Topic: ${formData.topic || "N/A"}`, margin, 100);
    doc.text(`Class: ${formData.classLevel || "N/A"}`, margin, 120);
    doc.text(`Total Marks: ${formData.totalMarks || "N/A"}`, margin, 140);
    doc.text(`Difficulty: ${formData.difficulty || "N/A"}`, margin, 160);
    doc.text(`Pattern: ${formData.pattern || "N/A"}`, margin, 180);

    doc.setLineWidth(0.5);
    doc.line(margin, 190, pageWidth - margin, 190);

    doc.setFont("Times", "normal");
    doc.setFontSize(12);
    let y = 210;

    // 🧾 Clean up text
    const cleanText = generatedPaper
      .replace(/\*\*/g, "")
      .replace(/##/g, "")
      .replace(/\*/g, "•")
      .replace(/Answer:/g, "\nAnswer:");

    // 🧮 Objective Pattern -> Table Format
    if (formData.pattern === "Only Objective") {
      const questions = cleanText.split(/\n\d+\./).filter((q) => q.trim().length > 0);
      const tableData = questions.map((q, i) => [i + 1, q.trim()]);

      autoTable(doc, {
        startY: y,
        head: [["No.", "Question"]],
        body: tableData,
        styles: { fontSize: 10, cellPadding: 5, valign: "top" },
        headStyles: { fillColor: [91, 75, 138], textColor: 255 },
      });
    } else {
      // 🧩 Text formatting for descriptive/mixed patterns
      const sections = cleanText.split(/\n\s*\n/);
      for (let section of sections) {
        if (y > 750) {
          doc.addPage();
          y = 60;
        }

        // Bold section headers like "Section A"
        if (/Section\s+[A-Z]/.test(section)) {
          doc.setFont("Helvetica", "bold");
          doc.setFontSize(14);
          doc.text(section.trim(), margin, y);
          y += 25;
          doc.setFont("Times", "normal");
          doc.setFontSize(12);
        } else {
          const lines = doc.splitTextToSize(section.trim(), pageWidth - margin * 2);
          doc.text(lines, margin, y);
          y += lines.length * 16 + 10;
        }
      }
    }

    // 📦 Footer
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Page ${i} of ${totalPages}`, centerX, 820, { align: "center" });
      doc.text("Generated by PaperGenX", centerX, 805, { align: "center" });
    }

    doc.save(`Question_Paper_${formData.topic || "Generated"}.pdf`);
  };

  return (
    <div style={{ backgroundColor: "#ede7d0ff", minHeight: "100vh" }}>
      <Header />

      <div className="container py-5">
        <div className="row justify-content-center">
          <div className="col-12 col-lg-8">
            <div className="card shadow-lg border-0 rounded-4">
              <div className="card-body p-4">
                <h2 className="fw-bold text-center mb-3" style={{ color: "#5b4b8a" }}>
                  Generate Question Paper
                </h2>
                <p className="text-center text-muted mb-4">
                  Enter your topic and preferences to create a custom question paper.
                </p>

                <form onSubmit={handleGenerate}>
                  <div className="row">
                    <div className="col-md-12 mb-3">
                      <label className="form-label fw-semibold">Topic *</label>
                      <input
                        type="text"
                        name="topic"
                        className="form-control form-control-lg rounded-3"
                        placeholder="e.g. Photosynthesis, Algebra, World War II"
                        value={formData.topic}
                        onChange={handleChange}
                      />
                    </div>

                    <div className="col-md-6 mb-3">
                      <label className="form-label fw-semibold">Class *</label>
                      <select
                        name="classLevel"
                        className="form-select form-select-lg rounded-3"
                        value={formData.classLevel}
                        onChange={handleChange}
                      >
                        <option value="">Select class</option>
                        {[6, 7, 8, 9, 10, 11, 12].map((cls) => (
                          <option key={cls} value={cls}>
                            Class {cls}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div className="col-md-6 mb-3">
                      <label className="form-label fw-semibold">Total Marks *</label>
                      <select
                        name="totalMarks"
                        className="form-select form-select-lg rounded-3"
                        value={formData.totalMarks}
                        onChange={handleChange}
                      >
                        <option value="">Select total marks</option>
                        {[25, 50, 75, 100].map((mark) => (
                          <option key={mark} value={mark}>
                            {mark}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div className="col-md-6 mb-3">
                      <label className="form-label fw-semibold">Difficulty Level *</label>
                      <select
                        name="difficulty"
                        className="form-select form-select-lg rounded-3"
                        value={formData.difficulty}
                        onChange={handleChange}
                      >
                        <option value="">Select difficulty</option>
                        {["Easy", "Medium", "Hard"].map((lvl) => (
                          <option key={lvl} value={lvl}>
                            {lvl}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div className="col-md-6 mb-4">
                      <label className="form-label fw-semibold">Question Paper Pattern</label>
                      <select
                        name="pattern"
                        className="form-select form-select-lg rounded-3"
                        value={formData.pattern}
                        onChange={handleChange}
                      >
                        <option value="">Select pattern</option>
                        <option value="MCQ + Short + Long">MCQ + Short + Long</option>
                        <option value="Only Descriptive">Only Descriptive</option>
                        <option value="Only Objective">Only Objective</option>
                        <option value="Mixed Format">Mixed Format</option>
                      </select>
                    </div>
                  </div>

                  {error && <p className="text-danger text-center">{error}</p>}

                  {isloading ? (
                    <button className="btn btn-dark w-100 mb-3" type="button" disabled>
                      <span
                        className="spinner-border spinner-border-sm"
                        aria-hidden="true"
                      ></span>
                      <span role="status" className="ms-2">
                        Generating...
                      </span>
                    </button>
                  ) : (
                    <button type="submit" className="btn btn-dark w-100 mb-3">
                      Generate Paper
                    </button>
                  )}
                </form>

                {generatedPaper && (
                  <div className="mt-5 bg-light p-4 rounded-4 shadow-sm">
                    <h4 className="fw-bold mb-3 text-center text-dark">
                      Generated Question Paper
                    </h4>
                    <pre
                      className="p-3 bg-white rounded-4 border"
                      style={{
                        whiteSpace: "pre-wrap",
                        fontSize: "1rem",
                        fontFamily: "inherit",
                      }}
                    >
                      {generatedPaper}
                    </pre>

                    <div className="text-center mt-3">
                      <button className="btn btn-success" onClick={handleDownloadPDF}>
                        📄 Download as PDF
                      </button>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default GenPaper;
